---
- name: Install FreeIPA master (5-7 minutes)
  tags:
    - ipaserver-master
    - ipa-install
  command: >
    ipa-server-install -U
    --realm {{ ansible_domain | upper }}
    --domain {{ ansible_domain | lower }}
    --hostname {{ ansible_fqdn }}
    --ds-password {{ ipa_dm_password }}
    --admin-password {{ ipa_admin_password }}
    --ip-address {{ ansible_default_ipv4.address }}
    --setup-dns
    --mkhomedir
    --ssh-trust-dns
    --reverse-zone={{ reversezone.reversezone }}
    {{ '--forwarder=%s' % dns_forwarder['nameservers'][0] if enable_network else '--no-forwarders' }}
  when: not ipa_installed

- name: Install KRA on FreeIPA master (2-3 minutes)
  tags:
    - ipaserver-master
    - ipa-install
  command: >
    ipa-kra-install -U
    -p {{ ipa_dm_password }}
  args:
    creates: /etc/pki/pki-tomcat/kra/CS.cfg

# XXX workaround for race condition
# KRA restarts LDAP, which disconnects bind-ldap plugin. The reconnect
# interval is 60 seconds. A restart make sure named is working properly.
- name: Make sure named-pkcs11 DNS is restarted
  tags:
    - ipaserver-master
    - ipa-install
  service: name=named-pkcs11 state=restarted
  changed_when: false

- name: wait for services to come up
  tags:
    - ipaserver-master
    - ipa-install
  wait_for: port={{ item }} delay=0 timeout=30
  with_items:
    - 53
    - 88
    - 464
    - 749
    - 389
    - 636
    - 80
    - 443
    - 8080
    - 8443

- name: Use FreeIPA DNS, nmcli conn modify ipv4.dns
  tags:
    - ipaserver-master
    - ipa-install
  command: >
    nmcli conn modify {{ hostvars[item].nm_conn }} ipv4.dns
    "{{ hostvars[groups['ipaserver_master'][0]].ansible_default_ipv4.address }} {{ hostvars[groups['ipaserver_replica'][0]].ansible_default_ipv4.address }}"
  delegate_to: "{{item}}"
  with_items: "{{ ipa_hosts }}"
  changed_when: false

- name: Use FreeIPA DNS, nmcli conn modify ipv4.dns-search
  tags:
    - ipaserver-master
    - ipa-install
  command: >
    nmcli conn modify {{ hostvars[item].nm_conn }} ipv4.dns-search {{ ansible_domain }}
  delegate_to: "{{item}}"
  with_items: "{{ ipa_hosts }}"
  changed_when: false

- name: Use FreeIPA DNS, nmcli conn modify ipv4.ignore-auto-dns
  tags:
    - ipaserver-master
    - ipa-install
  command: >
    nmcli conn modify {{ hostvars[item].nm_conn }} ipv4.ignore-auto-dns yes
  delegate_to: "{{item}}"
  with_items: "{{ ipa_hosts }}"
  changed_when: false

- name: Restart NetworkManager to make DNS changes effective
  tags:
    - ipaserver-master
    - ipa-install
  service: name=NetworkManager state=restarted
  delegate_to: "{{item}}"
  with_items: "{{ ipa_hosts }}"
  changed_when: false

- name: Set sensible defaults
  tags:
    - ipaserver-master
    - ipa-install
  ipa:
    args="config-mod --defaultshell=/bin/bash"
    password="{{ ipa_admin_password }}"
    ignore_no_modifications=true

- name: Set home directory to /export/home
  tags:
    - ipaserver-master
    - ipa-install
  ipa:
    args="config-mod --homedirectory=/export/home"
    password="{{ ipa_admin_password }}"
    ignore_no_modifications=true

- name: Set admin's home directory to /export/home/admin
  tags:
    - ipaserver-master
    - ipa-install
  ipa:
    args="user-mod admin --homedir=/export/home/admin"
    password="{{ ipa_admin_password }}"
    ignore_no_modifications=true

- name: Enable password and OTP loging
  tags:
    - ipaserver-master
    - ipa-install
  ipa:
    args="config-mod --user-auth-type=password --user-auth-type=otp"
    password="{{ ipa_admin_password }}"
    ignore_no_modifications=true

- name: Enable global DNS sync ptr
  tags:
    - ipaserver-master
    - ipa-install
  ipa:
    args="dnsconfig-mod --allow-sync-ptr=TRUE"
    password="{{ ipa_admin_password }}"
    ignore_no_modifications=true

- name: Enable DNS sync ptr
  tags:
    - ipaserver-master
    - ipa-install
  ipa:
    args="dnszone-mod {{ ansible_domain }}. --allow-sync-ptr=TRUE"
    password="{{ ipa_admin_password }}"
    ignore_no_modifications=true

- name: Enable reverse DNS sync ptr
  tags:
    - ipaserver-master
    - ipa-install
  ipa:
    args="dnszone-mod {{ reversezone.reversezone }} --allow-sync-ptr=TRUE"
    password="{{ ipa_admin_password }}"
    ignore_no_modifications=true

- name: signal FreeIPA master has been deployed
  tags:
    - ipaserver-master
    - ipa-install
  copy:
    content="PKI playbook"
    dest=/etc/ipa/MASTER_DEPLOYED

- include: ../../ipa-client/tasks/ipaclientinstalled.yml

- name: Create Firefox prefs
  tags:
    - ipaserver-master
    - ipa-install
  template: src=firefox_prefs dest=/etc/ipa/prefs.js

- name: Create Firefox bookmarks
  tags:
    - ipaserver-master
    - ipa-install
  template: src=bookmarks.html dest=/etc/ipa/bookmarks.html

- name: Fetch Firefox files
  tags:
    - ipaserver-master
    - ipa-install
    - fetch
  fetch:
    src=/etc/ipa/{{ item }}
    dest={{ vagrant_root }}/inventory/{{ item }}
    flat=yes
  with_items:
    - prefs.js
    - bookmarks.html

- name: Write custom krb5.conf
  tags:
    - ipaserver-master
    - ipa-install
  template:
    src=../../ipa/templates/krb5.conf
    dest=/tmp/krb5.conf

- name: Fetch krb5config
  tags:
    - ipaserver-master
    - ipa-install
    - fetch
  fetch:
    src=/tmp/krb5.conf
    dest={{ vagrant_root }}/inventory/krb5.conf
    flat=yes

- name: Fetch resolv.conf
  tags:
    - ipaserver-master
    - ipa-install
    - fetch
  fetch:
    src=/etc/resolv.conf
    dest={{ vagrant_root }}/inventory/resolv.conf
    flat=yes

- name: Fetch cacert
  tags:
    - ipaserver-master
    - ipa-install
    - fetch
  fetch:
    src=/etc/ipa/ca.crt
    dest={{ vagrant_root }}/inventory/ca.crt
    flat=yes

- name: Fetch ipa default.conf
  tags:
    - ipaserver-master
    - ipa-install
    - fetch
  fetch:
    src=/etc/ipa/default.conf
    dest={{ vagrant_root }}/inventory/default.conf
    flat=yes

- name: Fetch kra agent pem file
  tags:
    - ipaserver-master
    - ipa-install
    - fetch
  fetch:
    src=/etc/httpd/alias/kra-agent.pem
    dest={{ vagrant_root }}/inventory/kra-agent.pem
    flat=yes
