---
- name: install Apache modules
  tags:
    - ipa-httpexample
    - package-install
    - network
  yum: name={{ item }} state=present
  with_items:
    - mod_auth_gssapi
    - mod_authnz_pam
    - mod_intercept_form_submit
    - mod_lookup_identity
    - libsss_simpleifp
    - sssd-dbus
    - mod_nss
    - mod_session
  when: package_install
  notify:
    - restart httpd
    - restart sssd

- name: setsebool allow_httpd_mod_auth_pam on
  tags:
    - ipa-httpexample
    - ipa-install
  seboolean: name=httpd_mod_auth_pam state=yes persistent=yes
  notify:
    - restart httpd

- name: setsebool httpd_dbus_sssd on
  tags:
    - ipa-httpexample
    - ipa-install
  seboolean: name=httpd_dbus_sssd state=yes persistent=yes
  notify:
    - restart httpd

- name: Enable rewrite engine for nss.conf
  tags:
    - ipa-httpexample
    - ipa-install
  lineinfile:
    dest=/etc/httpd/conf.d/nss.conf
    regexp='^RewriteEngine'
    line='RewriteEngine On'
    insertafter='^NSSEngine'
  notify:
    - restart httpd

- name: Add rewrite rule for / to nss.conf
  tags:
    - ipa-httpexample
    - ipa-install
  lineinfile:
    dest=/etc/httpd/conf.d/nss.conf
    regexp='^RewriteRule'
    line='RewriteRule ^/$ https://{{ ansible_fqdn }}/example [L,NC,R=301]'
    insertafter='^RewriteEngine'
  notify:
    - restart httpd

# SSSD
- name: Add ldap_user_extra_attrs to sssd.conf
  tags:
    - ipa-httpexample
    - ipa-install
  ini_file:
    dest=/etc/sssd/sssd.conf
    section="domain/{{ ipa.domain }}"
    option=ldap_user_extra_attrs
    value="mail, givenname, sn"
  notify:
    - restart sssd
    - flush sssd

- name: Add [ifp]allowed_uids to sssd.conf
  tags:
    - ipa-httpexample
    - ipa-install
  ini_file:
    dest=/etc/sssd/sssd.conf
    section="ifp"
    option=allowed_uids
    value="apache, root"
  notify:
    - restart sssd
    - flush sssd

- name: Add [ifp]user_attributes to sssd.conf
  tags:
    - ipa-httpexample
    - ipa-install
  ini_file:
    dest=/etc/sssd/sssd.conf
    section="ifp"
    option=user_attributes
    value="+mail, +givenname, +sn"
  notify:
    - restart sssd
    - flush sssd

# XXX may override additional values
- name: Add [ifp]user_attributes to sssd.conf
  tags:
    - ipa-httpexample
    - ipa-install
  ini_file:
    dest=/etc/sssd/sssd.conf
    section="sssd"
    option=services
    value="nss, sudo, pam, autofs, ssh, ifp"
  notify:
    - restart sssd
    - flush sssd

# Example app
- name: Create Apache config for example
  tags:
    - ipa-httpexample
    - ipa-install
  template:
    src=example.conf
    dest=/etc/httpd/conf.d/example.conf
  notify:
    - restart httpd

- name: Copy Apache example app files
  tags:
    - ipa-httpexample
    - ipa-install
  copy:
    src=example/
    dest=/srv/www/example/
    mode=0644
    directory_mode=0755
    owner=root
    group=root
    seuser=system_u
    serole=object_r
    setype=httpd_sys_content_t
    selevel=s0
  notify:
    - restart httpd

- name: Create Apache example app
  tags:
    - ipa-httpexample
    - ipa-install
  template:
    src=wsgi.py
    dest=/srv/www/example/wsgi.py
    mode=0644
    directory_mode=0755
    owner=root
    group=root
    seuser=system_u
    serole=object_r
    setype=httpd_sys_content_t
    selevel=s0
  notify:
    - restart httpd

- name: Create PAM service for Apache example app
  tags:
    - ipa-httpexample
    - ipa-install
  template:
    src=pam_http_example
    dest=/etc/pam.d/http_example
  notify:
    - restart httpd
