---
- name: install pki-server packages and dependencies
  tags:
    - pki
    - packages
    - network
  yum: name={{ item }} state=present
  with_items:
    - pki-server
    - dogtag-pki-server-theme
    - openssl
  when: network_access

- name: Open Firewall for services
  tags:
    - pki
    - firewall
  firewalld: 
    service={{ item }}
    permanent=true
    state=enabled
    immediate=yes
  with_items:
    - ssh
    - ldap
    - ldaps
  when: has_firewalld.stat.exists

- name: Open Firewall for ports
  tags:
    - pki
    - firewall
  firewalld:
    port={{ item }}
    permanent=true
    state=enabled
    immediate=yes
  with_items:
    - 8080/tcp
    - 8443/tcp
  when: has_firewalld.stat.exists

