---
# configure as client first, then promote to replica
- include: ../../ipa-client/tasks/main.yml

# workaround for https://pagure.io/freeipa/issue/6704
- name: Stop Apache HTTPD to free port 8443 for installation
  tags:
    - ipaserver-replica
    - ipa-install
  service:
    name=httpd
    state=stopped
  when: not ipa.configured.server

- name: install replica
  tags:
    - ipaserver-replica
    - ipa-install
  command: >
    ipa-replica-install -U
    --admin-password {{ ipa_admin_password }}
    --mkhomedir
    --ip-address {{ ansible_default_ipv4.address }}
    --setup-dns
    --allow-zone-overlap
    --skip-conncheck
    {{ '--forwarder=%s' % dns_forwarder['nameservers'][0] if enable_network else '--no-forwarders' }}
  when: not ipa.configured.server
