---
- name: safe-guard against race condition
  any_errors_fatal: true
  hosts: all
  pre_tasks:
    # https://github.com/mitchellh/vagrant/issues/6526
    - name: "wait for the node to be ready"
      tags:
        - bootstrap
      become: false
      local_action: wait_for host={{ ansible_ssh_host }} port={{ ansible_ssh_port }} delay=1

# Use roles instead of meta to parallelize common tasks
- name: install IPA base system
  any_errors_fatal: true
  hosts: all
  roles:
    - ipa

- name: install IPA server system
  any_errors_fatal: true
  hosts:
    - ipaserver_master
    - ipaserver_replica
  roles:
    - ipaserver

- name: install FreeIPA server master
  hosts:
    - ipaserver_master
  roles:
    - ipaserver-master

- name: create local inventory files
  hosts:
    - ipaserver_master
  roles:
    - ipa-inventory

- name: install FreeIPA server replica
  hosts:
    - ipaserver_replica
  roles:
    - ipaserver-replica

- name: install FreeIPA client
  any_errors_fatal: true
  hosts:
   - ipa_client
   - ipa_nfsserver
   - ipa_smbserver
   - ipa_vpnserver
   - ipa_httpexample
   - ipa_ipsilon_idp
  roles:
    - ipa-client
  # workaround for join race-condition in 4.3.0
  serial: 1

- name: install OpenConnect VPN server for FreeIPA
  hosts:
    - ipa_vpnserver
  roles:
    - ipa-vpnserver

- name: install FreeIPA NFS server
  hosts:
    - ipa_nfsserver
  roles:
    - ipa-nfsserver

- name: install FreeIPA Samba server
  hosts:
    - ipa_smbserver
  roles:
    - ipa-smbserver

- name: install FreeIPA HTTP example app
  hosts:
    - ipa_httpexample
  roles:
    - ipa-httpexample

- name: install Ipsilon Identity Provider
  hosts:
    - ipa_ipsilon_idp
  roles:
    - ipa-ipsilon-idp

- name: install Ipsilon SP example
  hosts:
    - ipa_sp_example
  roles:
    - ipa-sp-example
